name: Glacier-Core
version: 1.0.0
main: com.joeyblankendaal.glacier.core.Main
author: Joey Blankendaal

commands:
  heal:
    description: Sets a player's health to 20, restoring it fully.
  more:
    description: Sets the amount of the item in a player's hand to 64.
  weathers:
    description: Sets a world's weather to either sunny or stormy.